# Generated by Django 3.0.4 on 2020-03-20 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to=None)),
                ('description', models.CharField(max_length=500)),
                ('inventory_count', models.PositiveSmallIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_posted', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('shipping_addr', models.CharField(blank=True, max_length=200)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('pId', models.IntegerField(primary_key=True, serialize=False)),
                ('shipping_addr', models.CharField(max_length=200)),
                ('total_amt', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pDate', models.DateField()),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.User')),
                ('iId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Item')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.User'),
        ),
    ]
