# Generated by Django 3.0.4 on 2020-04-15 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vueapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='artist',
            field=models.CharField(default='utc', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='title',
            field=models.CharField(default='utc', max_length=50),
            preserve_default=False,
        ),
    ]
