# Generated by Django 3.0.4 on 2020-04-03 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vueapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='photo',
            field=models.ImageField(upload_to='albumart'),
        ),
    ]
