# Generated by Django 3.0.4 on 2020-04-15 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vueapi', '0002_auto_20200414_2018'),
        ('vueapi', '0002_auto_20200415_0219'),
    ]

    operations = [
    ]
