# Generated by Django 3.0.4 on 2020-04-19 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vueapi', '0003_merge_20200415_1546'),
        ('vueapi', '0002_auto_20200414_2019'),
    ]

    operations = [
    ]
