# Generated by Django 3.0.4 on 2020-04-19 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import vueapi.models


class Migration(migrations.Migration):

    dependencies = [
        ('vueapi', '0004_merge_20200418_2358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(validators=[vueapi.models.validate_content_message])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
