# Generated by Django 3.0.4 on 2020-04-22 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vueapi', '0004_merge_20200421_0050'),
        ('vueapi', '0005_message'),
    ]

    operations = [
    ]
